using Zadanie_domowe;

var employee = new Employee("Jan", "Nowak");
employee.AddGrade("200");
employee.AddGrade(29.64574567);
employee.AddGrade(5);
var statistics = employee.GetStatisticsWithForEatch();
Console.WriteLine($"Imię : {employee.name}  Nazwisko : {employee.surname}");
Console.WriteLine(" OCENY liczone metodą GetStatisticsWithForEatch");
Console.WriteLine($"Minimalna  {statistics.Min:N2}");
Console.WriteLine($"Maksymalna {statistics.Max:N2}");
Console.WriteLine($"Średnia    {statistics.Average:N2}");
statistics = employee.GetStatisticsWithFor();
Console.WriteLine();
Console.WriteLine(" OCENY liczone metodą GetStatisticsWithFor");
Console.WriteLine($"Minimalna  {statistics.Min:N2}");
Console.WriteLine($"Maksymalna {statistics.Max:N2}");
Console.WriteLine($"Średnia    {statistics.Average:N2}");
statistics = employee.GetStatisticsWithWhil();
Console.WriteLine();
Console.WriteLine(" OCENY liczone metodą GetStatisticsWithWhil");
Console.WriteLine($"Minimalna  {statistics.Min:N2}");
Console.WriteLine($"Maksymalna {statistics.Max:N2}");
Console.WriteLine($"Średnia    {statistics.Average:N2}");
statistics = employee.GetStatisticsWithDoWhil();
Console.WriteLine();
Console.WriteLine(" OCENY liczone mctodą GetStatisticsWithDoWhil");
Console.WriteLine($"Minimalna  {statistics.Min:N2}");
Console.WriteLine($"Maksymalna {statistics.Max:N2}");
Console.WriteLine($"Średnia    {statistics.Average:N2}");